version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: always
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo123
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
