version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bdavanzada-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/dvdrental.tar:/docker-entrypoint-initdb.d/dvdrental.tar
      - ./docker/entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
    networks:
      - bdnet

volumes:  
  pgdata:

networks:
  bdnet:
